name: foolishgeorge
favicon: null
layout_spectrum: 0.4262945814989507
typography_spectrum: 0.09307526960037649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.04956498206593096
  lightness: 0.602264751913026
  saturation: 0.8408411943819374
  rhythmicContrast: 0.43104010657407343
purpose: []
